GRANT USAGE ON *.* TO `GlobalProj_admin`@`%`;
GRANT `database_administrator`@`%` TO `GlobalProj_admin`@`%`;
GRANT USAGE ON *.* TO `GlobalProj_client`@`%`;
GRANT `client`@`%` TO `GlobalProj_client`@`%`;
GRANT USAGE ON *.* TO `GlobalProj_testing`@`%`;
GRANT `testing`@`%` TO `GlobalProj_testing`@`%`;
GRANT USAGE ON *.* TO `GlobalProj_user`@`%`;
GRANT `end_user`@`%` TO `GlobalProj_user`@`%`;
GRANT USAGE ON *.* TO `client`@`%`;
GRANT SELECT ON `GlobalProj`.* TO `client`@`%`;
GRANT USAGE ON *.* TO `database_administrator`@`%`;
GRANT SELECT, INSERT, UPDATE, DELETE ON `GlobalProj`.* TO `database_administrator`@`%`;
GRANT USAGE ON *.* TO `end_user`@`%`;
GRANT SELECT, INSERT, UPDATE ON `GlobalProj`.* TO `end_user`@`%`;
GRANT USAGE ON *.* TO `testing`@`%`;
GRANT SELECT, UPDATE ON `GlobalProj`.* TO `testing`@`%`;
GRANT SELECT ON *.* TO `mysql.infoschema`@`localhost`;
GRANT SYSTEM_USER ON *.* TO `mysql.infoschema`@`localhost`;
GRANT SHUTDOWN, SUPER ON *.* TO `mysql.session`@`localhost`;
GRANT BACKUP_ADMIN,CLONE_ADMIN,CONNECTION_ADMIN,PERSIST_RO_VARIABLES_ADMIN,SESSION_VARIABLES_ADMIN,SYSTEM_USER,SYSTEM_VARIABLES_ADMIN ON *.* TO `mysql.session`@`localhost`;
GRANT SELECT ON `performance_schema`.* TO `mysql.session`@`localhost`;
GRANT SELECT ON `mysql`.`user` TO `mysql.session`@`localhost`;
GRANT USAGE ON *.* TO `mysql.sys`@`localhost`;
GRANT SYSTEM_USER ON *.* TO `mysql.sys`@`localhost`;
GRANT TRIGGER ON `sys`.* TO `mysql.sys`@`localhost`;
GRANT SELECT ON `sys`.`sys_config` TO `mysql.sys`@`localhost`;
GRANT USAGE ON *.* TO `testuser`@`localhost`;
